### ISSUE TITLE
How to mount the necessary nvswitch devices and libnvidia-nscq files within the dcgm-exporter container.

### ISSUE THREAD

**Issue by lyj8330328** [NVIDIA/dcgm-exporter#169]
INFO[0000] Starting dcgm-exporter
INFO[0000] DCGM successfully initialized!
INFO[0000] Collecting DCP Metrics
INFO[0000] No configmap data specified, falling back to metric file /etc/dcgm-exporter/default-counters.csv
INFO[0000] Initializing system entities of type: GPU
INFO[0001] Initializing system entities of type: NvSwitch
INFO[0001] Not collecting switch metrics: no switches to monitor
INFO[0001] Initializing system entities of type: NvLink
INFO[0001] Not collecting link metrics: no switches to monitor
INFO[0001] Kubernetes metrics collection enabled!
INFO[0001] Pipeline starting
INFO[0001] Starting webserver

device:
drwxr-xr-x  2 root root      100 Jun 15 16:31 nvidia-caps/
crw-rw-rw-  1 root root 195, 254 Jun 15 16:31 nvidia-modeset
crw-rw-rw-  1 root root 236,   0 Jun 15 16:31 nvidia-nvlink
crw-rw-rw-  1 root root 235,   0 Jun 15 16:31 nvidia-nvswitch0
crw-rw-rw-  1 root root 235,   1 Jun 15 16:31 nvidia-nvswitch1
crw-rw-rw-  1 root root 235,   2 Jun 15 16:31 nvidia-nvswitch2
crw-rw-rw-  1 root root 235,   3 Jun 15 16:31 nvidia-nvswitch3
crw-rw-rw-  1 root root 235,   4 Jun 15 16:31 nvidia-nvswitch4
crw-rw-rw-  1 root root 235,   5 Jun 15 16:31 nvidia-nvswitch5
crw-rw-rw-  1 root root 235, 255 Jun 15 16:31 nvidia-nvswitchctl

libnvidia-nscq

lrwxrwxrwx 1 root root      19 Jun 15 16:35 libnvidia-nscq.so -> libnvidia-nscq.so.1*
lrwxrwxrwx 1 root root      21 Jun 15 16:35 libnvidia-nscq.so.1 -> libnvidia-nscq.so.1.2*
lrwxrwxrwx 1 root root      28 Jun 15 16:35 libnvidia-nscq.so.1.2 -> libnvidia-nscq.so.470.129.06*
-rwxr-xr-x 1 root root 1139720 May 13  2022 libnvidia-nscq.so.470.129.06*

**Comment by glowkey** [comment]
You'll need libnvidia-nscq.so.2 and at least driver 525. This script may be useful for getting started:

```
#!/usr/bin/env bash
FILES=(/usr/lib/x86_64-linux-gnu/libnvidia-nscq.so.530.30.02 \
       /usr/lib/x86_64-linux-gnu/libnvidia-nscq.so.2.0 \
       /usr/lib/x86_64-linux-gnu/libnvidia-nscq.so.2 \
       /usr/lib/x86_64-linux-gnu/libnvidia-nscq.so)
FILE_OPTS=$(for i in  ${FILES[*]}; do printf '%s ' "--mount src=$i,dst=$i,type=bind"; done)
DEVICES=(/dev/nvidia-nvswitch* /dev/nvidia-nvlink)
DEVICE_OPTS=$(for i in ${DEVICES[*]}; do printf '%s ' "--device $i"; done)

docker run \
        --name dcgm-exporter \
        --network host \
        $DEVICE_OPTS \
        --cap-add SYS_ADMIN \
        --gpus all \
        $FILE_OPTS \
        -d \
        --restart unless-stopped \
        nvidia/dcgm-exporter:3.1.8-3.1.5-ubuntu20.04 -f /etc/dcgm-exporter/dcp-metrics-included.csv
```

It's easier, however, to run DCGM on the host and connect to it from the container as outlined here: https://docs.nvidia.com/datacenter/cloud-native/gpu-telemetry/latest/dcgm-exporter.html#connecting-to-an-existing-dcgm-agent

**Comment by 152334H** [comment]
this does not work for me when i try it. 

```yml
services:
  dcgm-exporter:
    image: nvidia/dcgm-exporter:4.0.0-4.0.1-ubuntu22.04
    container_name: dcgm-exporter
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    devices:
      - /dev/nvidia-nvlink
      - /dev/nvidia-nvswitch0
      - /dev/nvidia-nvswitch1
      - /dev/nvidia-nvswitch2
      - /dev/nvidia-nvswitch3
      - /dev/nvidia-nvswitchctl
    volumes:
      - /usr/lib/x86_64-linux-gnu/libnvidia-nscq.so.550.144.03:/usr/lib/x86_64-linux-gnu/libnvidia-nscq.so.550.144.03:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-nscq.so.2.0:/usr/lib/x86_64-linux-gnu/libnvidia-nscq.so.2.0:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-nscq.so.2:/usr/lib/x86_64-linux-gnu/libnvidia-nscq.so.2:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-nscq.so:/usr/lib/x86_64-linux-gnu/libnvidia-nscq.so:ro
    ports:
      - "9400:9400"
    cap_add:
      - SYS_ADMIN
    command: ["-f", "/etc/dcgm-exporter/dcp-metrics-included.csv"]
    network_mode: host
    restart: unless-stopped
```

all filepaths in the above yaml exist on host. the container logs still state `Not collecting switch metrics: no switches to monitor` on retry
