### ISSUE TITLE
DCGM Exporter: Pending Pods

### ISSUE THREAD

**Issue by AndreOrlovE** [NVIDIA/dcgm-exporter#214]
Hi there, we are experience the following issue:
some pods of dcgm-exporter are stuck in Pending state for a long time

```
dcgm-exporter-zthrt                                               0/1     Pending             0              15h
dcgm-exporter-ztztt                                               0/1     Pending             0              26h
dcgm-exporter-zvgvp                                               0/1     Pending             0              13h
dcgm-exporter-zw725                                               1/1     Running             0              69d
dcgm-exporter-zwmst                                               0/1     Pending             0              18h
```

dcgm-exporter installed with Helm
```
apiVersion: v2
name: dcgm-exporter
version: 0.1.0
appVersion: "0.1.0"

dependencies:
- name: dcgm-exporter
  version: "3.2.0"
  repository: "https://nvidia.github.io/dcgm-exporter/helm-charts"
```

values.yaml

```
dcgm-exporter:
  enabled: true
  nameOverride: ""
  fullnameOverride: "dcgm-exporter"
  podAnnotations:
    "cluster-autoscaler.kubernetes.io/enable-ds-eviction": "true"
  nodeSelector:
    cloud.google.com/gke-gpu: "true"

  serviceMonitor:
    enabled: false

  resources:
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  tolerations:
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists

  securityContext:
    privileged: true 

  extraHostVolumes:
  - name: nvidia-install-dir-host
    hostPath: /home/kubernetes/bin/nvidia

  extraVolumeMounts:
  - name: nvidia-install-dir-host
    mountPath: /usr/local/nvidia

  extraEnv:
  - name: DCGM_EXPORTER_KUBERNETES
    value: "true"
  - name: "DCGM_EXPORTER_KUBERNETES_GPU_ID_TYPE"
    value: "device-name"

```

```
k describe pod dcgm-exporter-zthrt

Name:                 dcgm-exporter-zthrt
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Service Account:      dcgm-exporter
Node:                 gke-research-prod-cl-nap-a2-highgpu-1-d87baa6d-mbvw/
Labels:               app.kubernetes.io/component=dcgm-exporter
                      app.kubernetes.io/instance=dcgm-exporter-prod
                      app.kubernetes.io/name=dcgm-exporter
                      controller-revision-hash=6b744cdd96
                      pod-template-generation=7
Annotations:          cluster-autoscaler.kubernetes.io/enable-ds-eviction: true
Status:               Pending
IP:
IPs:                  <none>
Controlled By:        DaemonSet/dcgm-exporter
Containers:
  exporter:
    Image:      nvcr.io/nvidia/k8s/dcgm-exporter:3.3.0-3.2.0-ubuntu22.04
    Port:       9400/TCP
    Host Port:  0/TCP
    Args:
      -f
      /etc/dcgm-exporter/dcp-metrics-included.csv
    Requests:
      cpu:      100m
      memory:   128Mi
    Liveness:   http-get http://:9400/health delay=45s timeout=1s period=5s #success=1 #failure=3
    Readiness:  http-get http://:9400/health delay=45s timeout=1s period=10s #success=1 #failure=3
    Environment:
      DCGM_EXPORTER_KUBERNETES:              true
      DCGM_EXPORTER_LISTEN:                  :9400
      NODE_NAME:                              (v1:spec.nodeName)
      DCGM_EXPORTER_KUBERNETES:              true
      DCGM_EXPORTER_KUBERNETES_GPU_ID_TYPE:  device-name
    Mounts:
      /usr/local/nvidia from nvidia-install-dir-host (rw)
      /var/lib/kubelet/pod-resources from pod-gpu-resources (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9gpkd (ro)
Conditions:
  Type           Status
  PodScheduled   True
Volumes:
  pod-gpu-resources:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/pod-resources
    HostPathType:
  nvidia-install-dir-host:
    Type:          HostPath (bare host directory volume)
    Path:          /home/kubernetes/bin/nvidia
    HostPathType:
  kube-api-access-9gpkd:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              cloud.google.com/gke-gpu=true
Tolerations:                 :NoExecute op=Exists
                             :NoSchedule op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:                      <none>
```
I dont' see any events for this pod which prevent it for scheduling on specific node

we are using GKE and for this specific pod, for example, node already doesn't exist, but Pod keeps Pending

```
k get node gke-research-prod-cl-nap-a2-highgpu-1-d87baa6d-mbvw
Error from server (NotFound): nodes "gke-research-prod-cl-nap-a2-highgpu-1-d87baa6d-mbvw" not found
```

We also have another DeamonSets in the same namespace, but there is no such issue with them, so I suppose that it could be something wrong with the config of dcgm-exporter DS
