### ISSUE TITLE
Per pod metrics not exposed with time-slicing enabled

### ISSUE THREAD

**Issue by ThisIsQasim** [NVIDIA/dcgm-exporter#307]
### What is the version?

3.3.5-3.4.1

### What happened?

Metrics like `DCGM_FI_PROF_GR_ENGINE_ACTIVE` are only exposed for one single pod even though there are multiple pods that use the same GPU

### What did you expect to happen?

Metrics for the all the pods should be exposed

### What is the GPU model?

Tesla T4

### What is the environment?

GKE

### How to reproduce the issue?

- Enable time-slicing using device plugin
- Deploy DCGM and dcgm-exporter
- Deploy app that uses GPU
- Check metrics

### Anything else we need to know?

From the debug log
```
time="2024-04-05T13:49:04Z" level=debug msg="Device to pod mapping: map[nvidia0:{Name:gpu-pod-c69f6664f-vkkcb Namespace:default Container:extractor} nvidia0/vgpu0:{Name:gpu-pod-c69f6664f-vkkcb Namespace:default Container:extractor} nvidia0/vgpu1:{Name:gpu-pod-c69f6664f-2v922 Namespace:default Container:extractor} nvidia0/vgpu2:{Name:gpu-pod-c69f6664f-wrcxw Namespace:default Container:extractor} nvidia0/vgpu3:{Name:gpu-pod-c69f6664f-ffs8r Namespace:default Container:extractor}]"
```

**Comment by ThisIsQasim** [comment]
This appears to have been reported repeatedly #151 #201  #222

**Comment by nvvfedorov** [comment]
The performance metrics require exclusive access to GPU hardware with Turing architecture. If another pod tries to read performance metrics, the DCGM exporter cannot read performance metrics.

**Comment by ThisIsQasim** [comment]
there is only pod per node trying to read the metrics but multiple pods using the same GPU. The issue is that dcgm exporter should report metrics for all the pods using the GPU.

**Comment by ThisIsQasim** [comment]
Sure. A single GPU is advertised as multiple using the nvidia device plugin
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: time-slicing-config
data:
  any: |-
    version: v1
    flags:
      migStrategy: none
    sharing:
      timeSlicing:
        renameByDefault: false
        failRequestsGreaterThanOne: false
        resources:
          - name: nvidia.com/gpu
            replicas: 4
```
and then GPUs are requested with the regular resource requests
```
esources:
  requests:
    cpu: 3600m
  limits:
    memory: 13000Mi
    nvidia.com/gpu: "1"
```
