### ISSUE TITLE
Error starting nv-hostengine: DCGM initialization error

### ISSUE THREAD

**Issue by XDavidT** [NVIDIA/dcgm-exporter#34]
Run this command on a server with Nvidia A100 GPU, that one of them have MIG turned on:
`docker run  --gpus all --rm -p 9400:9400 nvcr.io/nvidia/k8s/dcgm-exporter:2.3.1-2.6.1-ubuntu20.04`
and the output I got:
```
Warning #2: dcgm-exporter doesn't have sufficient privileges to expose profiling metrics. To get profiling metrics with dcgm-exporter, use --cap-add SYS_ADMIN
time="2021-12-14T17:28:56Z" level=info msg="Starting dcgm-exporter"
CacheManager Init Failed. Error: -17
time="2021-12-14T17:28:56Z" level=fatal msg="Error starting nv-hostengine: DCGM initialization error"
```

Docker version 20.10.11, build dea9396
Ubuntu: VERSION="20.04.3 LTS (Focal Fossa)" x86_64
CPU: AMD
```
user@host~$ nvidia-smi
Tue Dec 14 17:30:37 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.29.05    Driver Version: 495.29.05    CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-PCI...  Off  | 00000000:0B:00.0 Off |                    0 |
| N/A   34C    P0    33W / 250W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-PCI...  Off  | 00000000:14:00.0 Off |                   On |
| N/A   30C    P0    32W / 250W |     20MiB / 40536MiB |     N/A      Default |
|                               |                      |              Enabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| MIG devices:                                                                |
+------------------+----------------------+-----------+-----------------------+
| GPU  GI  CI  MIG |         Memory-Usage |        Vol|         Shared        |
|      ID  ID  Dev |           BAR1-Usage | SM     Unc| CE  ENC  DEC  OFA  JPG|
|                  |                      |        ECC|                       |
|==================+======================+===========+=======================|
|  1    1   0   0  |     10MiB / 20096MiB | 42      0 |  3   0    2    0    0 |
|                  |      0MiB / 32767MiB |           |                       |
+------------------+----------------------+-----------+-----------------------+
|  1    2   0   1  |     10MiB / 20096MiB | 42      0 |  3   0    2    0    0 |
|                  |      0MiB / 32767MiB |           |                       |
+------------------+----------------------+-----------+-----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by nikkon-dev** [comment]
Hello,

Please, try to add `--cap-add=SYS_PTRACE --security-opt seccomp=unconfined` to the docker run command

WBR,
Nik

**Comment by XDavidT** [comment]
Working Thank you.

**Comment by nikkon-dev** [comment]
@Maellooou,

If you are talking about SYS_ADMIN capabilities or privileged mode, those are usually configured in the `securityContext` section.

**Comment by Maellooou** [comment]
Hi @nikkon-dev 

Thanks for your answer

I have some restriction on my kubernetes cluster. So I have to use PodSecurityPolicy to allow privileged.

I tried many think but I still have the issue 

```
Warning #2: dcgm-exporter doesn't have sufficient privileges to expose profiling metrics. To get profiling metrics with dcgm-exporter, use --cap-add SYS_ADMIN
time="2022-05-24T08:06:48Z" level=info msg="Starting dcgm-exporter"
Error: Failed to initialize NVML
time="2022-05-24T08:06:48Z" level=fatal msg="Error starting nv-hostengine: DCGM initialization error"
```

Here my daemonset configuration :
 ```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dcgm-exporter
  namespace: monitoring
  labels:
    app: dcgm-exporter
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: dcgm-exporter
  template:
    metadata:
      labels:
        app: dcgm-exporter
      name: dcgm-exporter
    spec:
      serviceAccountName: dcgm-service-account
      containers:
      - image: "nvcr.io/nvidia/k8s/dcgm-exporter:2.3.5-2.6.5-ubuntu20.04"
        imagePullPolicy: "IfNotPresent"
        args:
        - -f
        - /etc/dcgm-exporter/dcp-metrics-included.csv
        env:
        - name: "DCGM_EXPORTER_LISTEN"
          value: ":9400"
        - name: "DCGM_EXPORTER_KUBERNETES"
          value: "true"
        name: "dcgm-exporter"
        ports:
        - name: "metrics"
          containerPort: 9400
        volumeMounts:
        - name: "pod-gpu-resources"
          readOnly: true
          mountPath: "/var/lib/kubelet/pod-resources"
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
      volumes:
      - name: "pod-gpu-resources"
        hostPath:
          path: "/var/lib/kubelet/pod-resources"
```

Then my PSP and role 

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dcgm-psp-role
  namespace: monitoring
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - privileged
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["exporter-metrics-config-map"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dcgm-psp-binding
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dcgm-psp-role
subjects:
  - kind: ServiceAccount
    name: dcgm-service-account
    namespace: monitoring
```

```
kubectl get psp privileged -n monitoring
NAME         PRIV   CAPS   SELINUX    RUNASUSER   FSGROUP    SUPGROUP   READONLYROOTFS   VOLUMES
privileged   true   *      RunAsAny   RunAsAny    RunAsAny   RunAsAny   false            *
```

I opened a lot the PSP priviliged to be sure to have good right but it still doesn't work...

Do you have any idea of the issue ? 
Thanks a lot for your support
