### ISSUE TITLE
dgcm-exporter dont show metrics from any namespaces k8s

### ISSUE THREAD

**Issue by hive74** [NVIDIA/dcgm-exporter#363]
### Ask your question

Hello, 
There is `prometheus-server` in namespace `monitoring`, I've installed `dcgm-exporter 3.4.2` in namespace `gpu-exporter` on gpu-node. I was needed to add annotations `prometheus.io/scrape`, `prometheus.io/port: "9400"`, `prometheus.io/path: "metrics"` to dcgm pod and service. Also `prometheus-crd` was installed in ns `stack-kube`.
In the end, I get metrics in prometheus, for example, `DCGM_FI_DEV_GPU_UTIL` or `DCGM_FI_DEV_FB_USED`, but only one pod\service (self dcgm-exporter), I need to get metrics of other pods on this node (I have nvidia-smi exporter pod/service in same namespace and some different pods in any namespaces). How can I get it?

I tried to install `kube-prometheus-stack` in namespace `stack-kube` with `serviceMonitorSelectorNilUsesHelmValues: false`, I didnt have to create annotations for dcgm-exporter pod/service, but again get metrics of only dcgm-exporter pod/service

```
DCGM_FI_DEV_FB_USED{DCGM_FI_DRIVER_VERSION="550.54.15", Hostname="k8s-gpu1", app_kubernetes_io_component="dcgm-exporter", app_kubernetes_io_instance="dcgm-gpu-exporter", app_kubernetes_io_managed_by="Helm", app_kubernetes_io_name="dcgm-exporter", app_kubernetes_io_version="3.4.2", device="nvidia0", gpu="0", helm_sh_chart="dcgm-exporter-3.4.2", instance="172.16.140.27:9400", job="kubernetes-service-endpoints", modelName="NVIDIA RTX A5000", namespace="gpu-exporter", node="k8s-gpu1", service="dcgm-gpu-exporter-dcgm-exporter"}
DCGM_FI_DEV_FB_USED{DCGM_FI_DRIVER_VERSION="550.54.15", Hostname="k8s-gpu1", app_kubernetes_io_component="dcgm-exporter", app_kubernetes_io_instance="dcgm-gpu-exporter", app_kubernetes_io_name="dcgm-exporter", controller_revision_hash="85db9c866c", device="nvidia0", gpu="0", instance="172.16.140.27:9400", job="kubernetes-pods", modelName="NVIDIA RTX A5000", namespace="gpu-exporter", node="k8s-gpu1", pod="dcgm-gpu-exporter-dcgm-exporter-g54m2", pod_template_generation="7"}
```
`values.yaml` dcgm-exporter
```
# Labels to be added to dcgm-exporter pods
podLabels: {}

# Annotations to be added to dcgm-exporter pods
podAnnotations: #{}
# Using this annotation which is required for prometheus scraping
  prometheus.io/scrape: "true"
  prometheus.io/port: "9400"

# The SecurityContext for the dcgm-exporter pods
podSecurityContext: {}
  # fsGroup: 2000

# The SecurityContext for the dcgm-exporter containers
securityContext:
  privileged: true
  # readOnlyRootFilesystem: true

# Defines the dcgm-exporter service
service:
  # When enabled, the helm chart will create service
  enable: true
  type: ClusterIP
  port: 9400
  address: ":9400"
  # Annotations to add to the service
  annotations: #{}
    prometheus.io/scrape: "true"
    prometheus.io/port: "9400"
    prometheus.io/path: "metrics"

serviceMonitor:
  enabled: true
  interval: 15s
  honorLabels: false
  additionalLabels: {}
```

**Comment by nvvfedorov** [comment]
@hive74, try using `honorLabels: true`. The DCGM-Exporter and Prometheus scraper assign the same labels (namespace, pod, and container) to each metric. The `honorLabels: true` configuration helps to resolve the conflict.

**Comment by hive74** [comment]
@nvvfedorov thanks for reply.
I've tried, but there is no effect.
`prometheus-server` with annotations: nothing has changed (prometheus shows only pod/service of itself)
`kube-prometheus-stack` without annotations: nothing has changed (prometheus shows only pod/service of itself)

```
DCGM_FI_DEV_FB_USED{DCGM_FI_DRIVER_VERSION="550.54.15", Hostname="k8s-gpu1", app_kubernetes_io_component="dcgm-exporter", app_kubernetes_io_instance="dcgm-gpu-exporter", app_kubernetes_io_managed_by="Helm", app_kubernetes_io_name="dcgm-exporter", app_kubernetes_io_version="3.4.2", device="nvidia0", gpu="0", helm_sh_chart="dcgm-exporter-3.4.2", instance="172.16.140.23:9400", job="kubernetes-service-endpoints", modelName="NVIDIA RTX A5000", namespace="gpu-exporter", node="k8s-gpu1", service="dcgm-gpu-exporter-dcgm-exporter"}
DCGM_FI_DEV_FB_USED{DCGM_FI_DRIVER_VERSION="550.54.15", Hostname="k8s-gpu1", app_kubernetes_io_component="dcgm-exporter", app_kubernetes_io_instance="dcgm-gpu-exporter", app_kubernetes_io_name="dcgm-exporter", controller_revision_hash="ddc84c56b", device="nvidia0", gpu="0", instance="172.16.140.23:9400", job="kubernetes-pods", modelName="NVIDIA RTX A5000", namespace="gpu-exporter", node="k8s-gpu1", pod="dcgm-gpu-exporter-dcgm-exporter-n2r46", pod_template_generation="17"}
```


tried some `kube-prometheus-stack` configs:
```
    additionalScrapeConfigs: #[]
      - job_name: gpu-metrics
        scrape_interval: 1s
        metrics_path: /metrics
        scheme: http
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - gpu-operator
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          action: drop
          regex: .*-node-feature-discovery-master
        - source_labels: [__meta_kubernetes_pod_node_name]
          action: replace
          target_label: kubernetes_node
```

also I tried in `dcgm-exporter`
```
extraEnv: []
  - name: "DCGM_EXPORTER_KUBERNETES"
    value: "true"
  - name: "DCGM_EXPORTER_KUBERNETES_GPU_ID_TYPE"
    value: "device-name"
```

how do dcgm-exporter works? is there command via `nvidia-smi`, for example, to get gpu utilization per pod for all namespaces? or dcgm-exporter dont use nvidia-smi?

And is trouble on dcgm-side or prometheus-side? (that dcgm-exporter shows metrics only selfpod\service). Can I get metrics manually for another namespace pods at least?

**Comment by nvvfedorov** [comment]
@hive74, I think the issue lies in the Prometheus configuration. To confirm whether my assumption is correct, please run the following command within the DCGM-exporter pod: curl -v http://localhost:9400/metrics. If you see metrics with "namespace", "pod", and "container" other than DCGM-exporter itself, that means the DCGM-exporter works as expected, and you need to check your Prometheus configuration.

**Comment by hive74** [comment]
@nvvfedorov 
its good that we can check metrics without prometheus, but
`kubectl get endpoints -n gpu-exporter`

```
NAME                                        ENDPOINTS            AGE
endpoints/dcgm-gpu-exporter-dcgm-exporter   172.16.140.23:9400   5d17h
endpoints/nvidia-gpu-exporter               172.16.140.36:9835   7d17h
```
trying
`curl 172.16.140.23:9400/metrics`
and get
```
# HELP DCGM_FI_DEV_GPU_UTIL GPU utilization (in %).
# TYPE DCGM_FI_DEV_GPU_UTIL gauge
DCGM_FI_DEV_GPU_UTIL{gpu="0",UUID="GPU-7ad09335-aadb-19c3-e3a8",device="nvidia0",modelName="NVIDIA RTX A5000",Hostname="k8s-gpu1",DCGM_FI_DRIVER_VERSION="550.54.15"} 0
# HELP DCGM_FI_DEV_FB_USED Framebuffer memory used (in MiB).
# TYPE DCGM_FI_DEV_FB_USED gauge
DCGM_FI_DEV_FB_USED{gpu="0",UUID="GPU-7ad09335-aadb-19c3-e3a8",device="nvidia0",modelName="NVIDIA RTX A5000",Hostname="k8s-gpu1",DCGM_FI_DRIVER_VERSION="550.54.15"} 21383
```
and there is no `namespace`, `pod` and `container` in any metrics

**Comment by nvvfedorov** [comment]
@hive74 , Do you have [nvidia-device-plugin](https://github.com/NVIDIA/k8s-device-plugin?tab=readme-ov-file#deployment-via-helm) installed on your kubernetes cluster? This component is a source of information about namespaced, pod and containers assigned to GPUs.

**Comment by hive74** [comment]
@nvvfedorov 
Yes, `nvidia-device-plugin` is in any namespace
```
kubectl get pods -A | grep "nvidia"
gpu-exporter         nvidia-gpu-exporter-c7kz7                     1/1     Running                  0                   10d
jupyterhub           release-name-nvidia-device-plugin-55ssh       1/1     Running                  6 (66d ago)         408d
```
Can I check information about namespaces, pod and containers via `nvidia-device-plugin`? To confirm that plugin works correctly.

**Comment by hive74** [comment]
Additionally, I checked helm chart via `helm install --dry-run` and found that dcgm-exporter create `Role` and `RoleBinding`
Its ok? I thought that need more access like `ClusterRole` and `ClusterRoleBinding` 
```
---
# Source: dcgm-exporter/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dcgm-exporter-read-cm
  namespace: gpu-exporter
  labels:
    helm.sh/chart: dcgm-exporter-3.4.2
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/instance: dcgm-gpu-exporter
    app.kubernetes.io/version: "3.4.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "dcgm-exporter"
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["exporter-metrics-config-map"]
  verbs: ["get"]
---
# Source: dcgm-exporter/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dcgm-gpu-exporter-dcgm-exporter
  namespace: gpu-exporter
  labels:
    helm.sh/chart: dcgm-exporter-3.4.2
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/instance: dcgm-gpu-exporter
    app.kubernetes.io/version: "3.4.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "dcgm-exporter"
subjects:
- kind: ServiceAccount
  name: dcgm-gpu-exporter-dcgm-exporter
  namespace: gpu-exporter
roleRef:
  kind: Role 
  name: dcgm-exporter-read-cm
  apiGroup: rbac.authorization.k8s.io
```
