### ISSUE TITLE
DCGM_FI_DEV_GPU_UTIL for HPA is showing error "no metrics returned from custom metrics API"

### ISSUE THREAD

**Issue by MeghaVarshney21** [NVIDIA/dcgm-exporter#42]
Hi,

I have deployed triton on the top of Kubernetes (EKS). I've installed everything and is working well and I have created a HPA  as well for the triton deployment on the basis of GPU Utilization (DCGM_FI_DEV_GPU_UTIL).

The yaml file for HPA looks like this:-

```
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: triton
  namespace: prometheus
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: triton
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Pods
    pods:
      metricName: DCGM_FI_DEV_GPU_UTIL # Average GPU usage of the pod.
      targetAverageValue: 90

```

But, I have realized that it is not working.  It is showing me the error that "unable to get metric DCGM_FI_DEV_GPU_UTIL: no metrics returned from custom metrics API".

```
**kubectl describe hpa -n prometheus**

Name:                              triton
Namespace:                         prometheus
Labels:                            <none>
Annotations:                       <none>
CreationTimestamp:                 Sat, 05 Feb 2022 20:48:07 +0530
Reference:                         Deployment/triton
Metrics:                           ( current / target )
  "DCGM_FI_DEV_GPU_UTIL" on pods:  <unknown> / 90
Min replicas:                      1
Max replicas:                      3
Deployment pods:                   2 current / 2 desired
Conditions:
  Type           Status  Reason               Message
  ----           ------  ------               -------
  AbleToScale    True    SucceededGetScale    the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetPodsMetric  the HPA was unable to compute the replica count: unable to get metric DCGM_FI_DEV_GPU_UTIL: no metrics returned from custom metrics API
Events:
  Type     Reason               Age                     From                       Message
  ----     ------               ----                    ----                       -------
  Warning  FailedGetPodsMetric  4m33s (x9421 over 39h)  horizontal-pod-autoscaler  unable to get metric DCGM_FI_DEV_GPU_UTIL: no metrics returned from custom metrics API
```

**Comment by Tomer20** [comment]
I managed to achieve it using [KEDA Prometheus scaler](https://keda.sh/docs/2.10/scalers/prometheus/):

```yaml
triggers:
- type: prometheus
  metadata:
    serverAddress: http://<prometheus-host>:9090
    query: sum(rate(DCGM_FI_DEV_GPU_UTIL{exported_container=~"<your-container-using-gpu>"}[2m]))
    threshold: '90'
```
