### ISSUE TITLE
pod metric discontinuity

### ISSUE THREAD

**Issue by ltm920716** [NVIDIA/dcgm-exporter#428]
### What is the version?

newest

### What happened?

the metric of pod discontinuity like bellow：
![Image](https://github.com/user-attachments/assets/93ffe697-eb7e-46cc-869d-83a69de9823c)

### What did you expect to happen?

Continuous pod metric

### What is the environment?

pod

**Comment by ltm920716** [comment]
![Image](https://github.com/user-attachments/assets/5483e83b-6392-4cb4-94a6-82e4da4c0828)

**Comment by nvvfedorov** [comment]
The dcgm-exporter works in the following way: 
1. When there aren't pods running and using the specific GPU, the dcgm-exporter returns metrics without a pod label.
2. When a pod is running and using the specific GPU, the dcgm-exporter returns metrics with a pod label, to tell that this GPU was used by this pod. 

In other words, when you see metrics, without pod label, that means GPU does not run any pod at the moment.

**Comment by ltm920716** [comment]
> In other words, when you see metrics, without pod label, that means GPU does not run any pod at the moment.

hi @nvvfedorov ，

thanks for your reply，but the pods in the image all use gpus，some are LLM services that occupy certainty gpu memory（maybe utils is not alway > 0），and some are training jobs that utils > 0 always. You can see that the metric dismiss interval，so that is the point

**Comment by 22RC** [comment]
You need to add at `additional-scrape-configs.yaml` (in the secret of prometheus) scrape_interval to avoid using of default (30s)

```
- job_name: dcgm-exporter
  metrics_path: /metrics
  static_configs:
  - targets:
    - nvidia-dcgm-exporter.gpu-operator.svc:9400
  scrape_interval: 5s # Add this line
```
