### ISSUE TITLE
Move exporter-metrics-volume to daemonset.yaml

### ISSUE THREAD

**Issue by ysk24ok** [NVIDIA/dcgm-exporter#442]
### Is this a new feature, an improvement, or a change to existing functionality?

Change

### Please provide a clear description of the problem this feature solves

As of 3.3.9-3.6.1, `exporter-metrics-volume` configMapVolume and volumeMount is specified in values.yaml
https://github.com/NVIDIA/dcgm-exporter/blob/3.3.9-3.6.1/deployment/values.yaml#L143-L154

These are treated as default values, which mean you have to specify the `exporter-metrics-volume` in your values.yaml when you specify another volume because the default values are overridden.

For reference, here's my values.yaml. `nvidia-install-dir-host` volume is needed in my environment (ref: https://github.com/NVIDIA/dcgm-exporter/issues/385#issuecomment-2410921008).

```yaml
extraHostVolumes:
- name: nvidia-install-dir-host
  hostPath: /home/kubernetes/bin/nvidia
extraVolumeMounts:
- name: exporter-metrics-volume
  mountPath: /etc/dcgm-exporter/dcp-metrics-included.csv
  subPath: dcp-metrics-included.csv
- name: nvidia-install-dir-host
  mountPath: /usr/local/nvidia
  readOnly: true
```

### Feature Description

Uses don't have to specify `exporter-metrics-volume` in their values.yaml even when they have another volume.

### Describe your ideal solution

Moving `exporter-metrics-volume` configMapVolume and volumeMount out of values.yaml to templates/daemonset.yaml.

Since `exporter-metrics-volume` is required in any case, it makes sense if we have those values in the k8s yaml itself.
