### ISSUE TITLE
Cannot init NVML library; err: ERROR_LIBRARY_NOT_FOUND - GKE Cluster

### ISSUE THREAD

**Issue by leorniduv** [NVIDIA/dcgm-exporter#484]
### What is the version?

4.2.0-4.1.0

### What happened?

Hi,

When deploying the DCGM helm chart, I was running into an issue where the pods deployed by the daemonset weren't finding the nvidia utilities/libraries:

```
INFO Starting dcgm-exporter Version=4.1.1-4.0.4
INFO Attempting to initialize DCGM.
INFO Initialized DCGM Fields module.
INFO DCGM successfully initialized!
INFO Attempting to initialize NVML library.
ERROR Cannot init NVML library; err: ERROR_LIBRARY_NOT_FOUND # HERE
INFO NVML provider successfully initialized!
INFO Not collecting DCP metrics: This request is serviced by a module of DCGM that is not currently loaded
INFO Falling back to metric file '/etc/dcgm-exporter/default-counters.csv'
[...]
INFO Initializing system entities of type 'GPU'
INFO Not collecting GPU metrics; Error getting devices count: Cannot perform the requested operation because NVML doesn't exist on this system. # AND HERE
[...]
INFO Kubernetes metrics collection enabled!
INFO Starting webserver
INFO Listening on address=[::]:9400
INFO TLS is disabled. http2=false address=[::]:9400
```

I saw that this was very similar to [this issue](https://github.com/NVIDIA/dcgm-exporter/issues/448) and [this comment](https://github.com/NVIDIA/dcgm-exporter/issues/385#issuecomment-2410921008) from another issue (sadly the linked guide is 404 now).

I'm raising this issue because tag `4.1.1-4.0.4` does fix the problem, but problem seems to be back in the latest release `4.2.0-4.1.0` (at least from my tests, things only started working when I downgraded to `4.1.1-4.0.4`).

This seems to be linked to GKE clusters ? I'll provide more info on my infrastructure setup.

### What did you expect to happen?

Metrics being exported.

### What is the GPU model?

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.230.02             Driver Version: 535.230.02   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA L4                      Off | 00000000:00:03.0 Off |                    0 |
| N/A   73C    P0              33W /  72W |   5630MiB / 23034MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

```

### What is the environment?

Running in a pod on a GKE cluster:

- Node version: 1.30.10-gke.1070000
- COS version: cos-113-18244-291-40
- Machine type: g2-standard-8 + 1 x NVIDIA L4
- GPU driver installation mode: Default driver version (aka, I'm letting GCP take care of installing the drivers)

### How did you deploy the dcgm-exporter and what is the configuration?

Deployed using helm chart version `4.1.0`.

Here is the values.yaml file that **did not work**:
```yaml
# I don't need the SM, just wanted the metrics
serviceMonitor:
  enabled: false

securityContext:
  privileged: true

extraHostVolumes:
  - name: vulkan-icd-mount
    hostPath: /home/kubernetes/bin/nvidia/vulkan/icd.d
  - name: nvidia-install-dir-host
    hostPath: /home/kubernetes/bin/nvidia

extraVolumeMounts:
  - name: nvidia-install-dir-host
    mountPath: /usr/local/nvidia
    readOnly: true
  - name: vulkan-icd-mount
    mountPath: /etc/vulkan/icd.d
    readOnly: true

tolerations:
  - key: "nvidia.com/gpu"
    operator: "Equal"
    value: "present"
    effect: "NoSchedule"
```

Here is the version that worked:
```yaml
image:
  tag: 4.1.1-4.0.4-ubuntu22.04

# I don't need the SM, just wanted the metrics
serviceMonitor:
  enabled: false

securityContext:
  privileged: true

extraHostVolumes:
  - name: vulkan-icd-mount
    hostPath: /home/kubernetes/bin/nvidia/vulkan/icd.d
  - name: nvidia-install-dir-host
    hostPath: /home/kubernetes/bin/nvidia

extraVolumeMounts:
  - name: nvidia-install-dir-host
    mountPath: /usr/local/nvidia
    readOnly: true
  - name: vulkan-icd-mount
    mountPath: /etc/vulkan/icd.d
    readOnly: true

tolerations:
  - key: "nvidia.com/gpu"
    operator: "Equal"
    value: "present"
    effect: "NoSchedule"
```

### How to reproduce the issue?

I'm 80% sure that this only happens on GKE clusters, but don't really have any "proof" so I guess the only way is to try deploying the two values I shared in different clusters and seeing if the behavior is confirmed everywhere ? I'd be happy to test configs on my GCP cluster if it can help debugging.

### Anything else we need to know?

Again, I managed to get it working, just flagging that version `4.2.0-4.1.0` maybe brought back a bug fixed in `4.1.1-4.0.4`. I'd also be happy to add in the Readme a section on stuff to check/troubleshoot when you are on GKE 😄
