### ISSUE TITLE
Pod and namespace labels missing in metrics when using native sidecars

### ISSUE THREAD

**Issue by wesley-yep-canva** [NVIDIA/dcgm-exporter#497]
### What is the version?

4.1.1-4.0.4-ubuntu22.04

### What happened?

When running a pod where the GPU resource is on a native sidecar (initContainer with `restartPolicy: Always`), the `DCGM_*` metrics do not contain the namespace, pod, and container labels

When switching the gpu container to run as a normal container in the pod, the labels are showing as expected.

This lead me to believe it could be related to the kubelet client library versions but it seems like they're using a version later than 1.28 which is when support for native sidecars were added.

I also checked the kubelet unix socket using `grpcurl -plaintext --proto api.proto -unix /var/lib/kubelet/pod-resources/kubelet.sock v1.PodResourcesLister/List` and the native sidecar containers correctly show up in the pod containers list in the response, so shouldn't be an issue with the kubelet version.

### What did you expect to happen?

`DCGM_*` metrics contain the namespace, pod, and container labels for pods using native sidecar containers which are requesting GPUs.

### What is the GPU model?

Tested with T4 and L40S

### What is the environment?

EKS 1.30

### How did you deploy the dcgm-exporter and what is the configuration?

Using the helm chart

### How to reproduce the issue?

Create a pod with the following containers:
```
containers:
- image: nginx:1.26.0
  command: ["/bin/bash", "-c"]
  args:
    - |
      nginx -g 'daemon off;'
  name: non-gpu-container
initContainers:
- image: nginx:1.26.0
  command: ["/bin/bash", "-c"]
  args:
    - |
      while true; do sleep 10000; done       
  name: gpu-container
  resources:
    limits:
      nvidia.com/gpu: 1
    requests:
      nvidia.com/gpu: 1
  restartPolicy: Always
```

Once the pod comes up, check the metrics by port-forwarding `dcgm-exporter` pod, it contains only the hostname, e.g.:
```
DCGM_EXP_XID_ERRORS_COUNT{gpu="0",UUID="GPU-6302c971-f3a1-b3fe-257b-210fc853f6e1",pci_bus_id="00000000:30:00.0",device="nvidia0",modelName="NVIDIA L40S",Hostname="i-03852ff668a2f1457.ec2.internal",DCGM_FI_DRIVER_VERSION="535.247.01",window_size_in_ms="300000"} 0
```

Now repeat, with a spec with multiple containers instead of the native sidecar, e.g.
```
containers:
- image: index.docker.io/nginx:1.26.0
  command: ["/bin/bash", "-c"]
  args:
    - |
      nginx -g 'daemon off;'
  name: non-gpu-container
- image: 699983977898.dkr.ecr.us-east-1.amazonaws.com/mirror/index.docker.io/nginx:1.26.0
  command: ["/bin/bash", "-c"]
  args:
    - |
      while true; do sleep 10000; done       
  name: gpu-container
  resources:
    limits:
      nvidia.com/gpu: 1
    requests:
      nvidia.com/gpu: 1
```

Now check the metrics again and the labels are showing:
```
DCGM_EXP_XID_ERRORS_COUNT{gpu="0",UUID="GPU-6302c971-f3a1-b3fe-257b-210fc853f6e1",pci_bus_id="00000000:30:00.0",device="nvidia0",modelName="NVIDIA L40S",Hostname="i-03852ff668a2f1457.ec2.internal",DCGM_FI_DRIVER_VERSION="535.247.01",window_size_in_ms="300000",container="gpu-container",namespace="default",pod="xxxxxxxx-xxxxx-xxxxxx"} 0
```
