### ISSUE TITLE
Deployment by helm chart doesn't populate pod/container values

### ISSUE THREAD

**Issue by c-android** [NVIDIA/dcgm-exporter#63]
When I run the dcgm-exporter from the command line or a docker container on my GPU enabled host, "pod"and"container" show the names of the pods and container running my GPU application.

When I deploy with the helm chart,  "pod" and "container" are in the metrics but are always blank

`DCGM_FI_DEV_FB_FREE{gpu="0",UUID="GPU-<uuid>",device="nvidia0",modelName="<model>",Hostname="<pod name>",container="",namespace="",pod=""} 15007``

**Comment by nikkon-dev** [comment]
Could you check if the dcgm-exporter command line arguments have `-k` flag in the values.yaml of your helm chart?

**Comment by bhavika** [comment]
I also have this issue on Kubernetes and the `DCGM_EXPORTER_KUBERNETES ` flag is set to `true` in my case.

**Comment by nikkon-dev** [comment]
dcgm-exporter uses this API to get the pod resources info: https://pkg.go.dev/k8s.io/kubelet@v0.20.2/pkg/apis/podresources/v1alpha1

Just wondering, which k8s versions are you using?

**Comment by ravinaik-houzz** [comment]
+1 on this issue, we're also experiencing the same behavior where installation of the `dcgm-exporter` via the helm chart doesn't populate the pod/container name for the metrics.

Helm Chart Version: `v1.11.0` - latest - https://catalog.ngc.nvidia.com/orgs/nvidia/helm-charts/gpu-operator
Kubernetes version: `1.20.6`

Relevant values for the `dcgm-exporter` to confirm that the `DCGM_EXPORTER_KUBERNETES` value is set to `"true"`

```
dcgmExporter:
  repository: nvcr.io/nvidia/k8s
  image: dcgm-exporter
  version: 2.4.5-2.6.7-ubuntu20.04
  imagePullPolicy: IfNotPresent
  env:
    - name: DCGM_EXPORTER_LISTEN
      value: ":9400"
    - name: DCGM_EXPORTER_KUBERNETES
      value: "true"
    - name: DCGM_EXPORTER_COLLECTORS
      value: "/etc/dcgm-exporter/dcp-metrics-included.csv"
  resources: {}
```

Let me know if more data points are needed to investigate this issue. Thanks!
